### ISSUE TITLE
Re-Think Layout

### ISSUE THREAD

**Issue by ThePerfectComputer** [JoyOfHardware/FastWave2.0#7]
The commands window should likely be at the bottom of the window. It should actually be toggle-able - similar to the safari developer panel.

<img width="992" alt="image" src="https://github.com/JoyOfHardware/FastWave2.0/assets/103011002/74e9e9dc-1423-40ec-87a3-f349e1c207be">

See how the developer pane is docked at the bottom of Safari and can be toggle on and off?

<img width="1338" alt="image" src="https://github.com/JoyOfHardware/FastWave2.0/assets/103011002/9b7c54ca-467c-42ca-a68b-95be53e0f0b6">

**Comment by MartinKavik** [comment]
Update - commands panel moved down, toggleable in new design
